FROM golang:1.24.1-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o user-service ./cmd/main.go

FROM alpine:3.18 AS final

RUN apk add --no-cache bash

WORKDIR /root/

COPY --from=builder /app/user-service .
COPY --from=builder /app/.env .

CMD ["./user-service"]