services:
  user-service:
    build:
      context: .
      dockerfile: DockerFile
    container_name: user-service
    restart: always
    env_file:
      - .env
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: userdb
    volumes:
     - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - default-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 2s
      retries: 5

networks:
  default-network:
    driver: bridge

volumes:
  postgres-data: